name: adv_data_analytics3
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - jupyterlab
  - gensim=4.1.2
  - scikit-learn
  - datasets
  - ipywidgets
  - nltk
  - pytorch=1.10.2
  - scipy
  - transformers
  - matplotlib
